app:
  name: "account-balance-manager"
  version: "1.0.0"

http:
  port: 8080

log:
  level: "debug"

postgres:
  url: "user=root password=root host=localhost dbname=db sslmode=disable"
  max_pool_size: 1

hasher:
  salt: "salt"

jwt:
  sign_key: "secret"
  token_ttl: 120m
  