basePath: /
definitions:
  github_com_ArtemRotov_account-balance-manager_internal_model.User:
    properties:
      id:
        type: integer
      password:
        example: pass12345678
        maxLength: 30
        minLength: 6
        type: string
      username:
        example: example@mail.org
        type: string
    type: object
  internal_controller_http_v1.ErrorOutput:
    properties:
      error:
        example: example error
        type: string
    type: object
  internal_controller_http_v1.balanceInput:
    properties:
      user_id:
        type: integer
    type: object
  internal_controller_http_v1.balanceOutput:
    properties:
      balance:
        type: integer
      user_id:
        type: integer
    type: object
  internal_controller_http_v1.depositInput:
    properties:
      amount:
        type: integer
      user_id:
        type: integer
    type: object
  internal_controller_http_v1.depositOutput:
    properties:
      balance:
        type: integer
      user_id:
        type: integer
    type: object
  internal_controller_http_v1.signInOutput:
    properties:
      Token:
        example: eyJhbGc...
        type: string
    type: object
  internal_controller_http_v1.signUpOutput:
    properties:
      id:
        example: 1
        type: integer
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: rotoffff@yandex.ru
    name: Artem Rotov
    url: https://github.com/ArtemRotov
  description: My test service
  termsOfService: http://swagger.io/terms/
  title: My test service
  version: "1.0"
paths:
  /api/v1/account/:
    get:
      consumes:
      - application/json
      description: User balance
      parameters:
      - description: user_id
        in: body
        name: balanceInput
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_v1.balanceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.balanceOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
      summary: Balance
      tags:
      - api/v1/account
  /api/v1/account/deposit/:
    post:
      consumes:
      - application/json
      description: Deposit by userId
      parameters:
      - description: user_id, amount
        in: body
        name: depositInput
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_v1.depositInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.depositOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
      summary: Deposit
      tags:
      - api/v1/account/deposit
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Sign in
      parameters:
      - description: ID NO NEED
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_ArtemRotov_account-balance-manager_internal_model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.signInOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
      summary: Sign in
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign up
      parameters:
      - description: ID NO NEED
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_ArtemRotov_account-balance-manager_internal_model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_controller_http_v1.signUpOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.ErrorOutput'
      summary: Sign up
      tags:
      - auth
swagger: "2.0"
